//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNPS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.netvox.coms/", ConfigurationName="ServiceNPS.Call")]
    public interface Call
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.netvox.com/Call/registrarRequest", ReplyAction="http://soap.netvox.com/Call/registrarResponse")]
        System.Threading.Tasks.Task<ServiceNPS.registrarResponse> registrarAsync(ServiceNPS.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.netvox.com/Call/getCredencialesRequest", ReplyAction="http://soap.netvox.com/Call/getCredencialesResponse")]
        System.Threading.Tasks.Task<ServiceNPS.getCredencialesResponse> getCredencialesAsync(ServiceNPS.getCredencialesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar", Namespace="http://soap.netvox.com/", Order=0)]
        public ServiceNPS.registrarRequestBody Body;
        
        public registrarRequest()
        {
        }
        
        public registrarRequest(ServiceNPS.registrarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ges_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ges_campana;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ges_tipo_documento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ges_numero_documento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ges_fec_hor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pr_nombres_cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pr_apellidos_cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string desc_operador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string attributeconnid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string base_pto_contacto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ges_tipo_llamada;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ges_tipo_llamada_desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string id_res_cod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string res_desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string codigo_del_servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string descripcion_corta_servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string cod_detalle_servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string descripcion_corta_detalle_serv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string campana_ivrvox;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string identificador_empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string identificador_agente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string nombre_coordinador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string cod_personal;
        
        public registrarRequestBody()
        {
        }
        
        public registrarRequestBody(
                    string ges_id, 
                    string ges_campana, 
                    string ges_tipo_documento, 
                    string ges_numero_documento, 
                    string ges_fec_hor, 
                    string pr_nombres_cliente, 
                    string pr_apellidos_cliente, 
                    string desc_operador, 
                    string attributeconnid, 
                    string mensaje, 
                    string base_pto_contacto, 
                    string ges_tipo_llamada, 
                    string ges_tipo_llamada_desc, 
                    string id_res_cod, 
                    string res_desc, 
                    string codigo_del_servicio, 
                    string descripcion_corta_servicio, 
                    string cod_detalle_servicio, 
                    string descripcion_corta_detalle_serv, 
                    string telefono, 
                    string campana_ivrvox, 
                    string identificador_empresa, 
                    string identificador_agente, 
                    string nombre_coordinador, 
                    string cod_personal)
        {
            this.ges_id = ges_id;
            this.ges_campana = ges_campana;
            this.ges_tipo_documento = ges_tipo_documento;
            this.ges_numero_documento = ges_numero_documento;
            this.ges_fec_hor = ges_fec_hor;
            this.pr_nombres_cliente = pr_nombres_cliente;
            this.pr_apellidos_cliente = pr_apellidos_cliente;
            this.desc_operador = desc_operador;
            this.attributeconnid = attributeconnid;
            this.mensaje = mensaje;
            this.base_pto_contacto = base_pto_contacto;
            this.ges_tipo_llamada = ges_tipo_llamada;
            this.ges_tipo_llamada_desc = ges_tipo_llamada_desc;
            this.id_res_cod = id_res_cod;
            this.res_desc = res_desc;
            this.codigo_del_servicio = codigo_del_servicio;
            this.descripcion_corta_servicio = descripcion_corta_servicio;
            this.cod_detalle_servicio = cod_detalle_servicio;
            this.descripcion_corta_detalle_serv = descripcion_corta_detalle_serv;
            this.telefono = telefono;
            this.campana_ivrvox = campana_ivrvox;
            this.identificador_empresa = identificador_empresa;
            this.identificador_agente = identificador_agente;
            this.nombre_coordinador = nombre_coordinador;
            this.cod_personal = cod_personal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarResponse", Namespace="http://soap.netvox.com/", Order=0)]
        public ServiceNPS.registrarResponseBody Body;
        
        public registrarResponse()
        {
        }
        
        public registrarResponse(ServiceNPS.registrarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registrarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public registrarResponseBody()
        {
        }
        
        public registrarResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCredencialesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCredenciales", Namespace="http://soap.netvox.com/", Order=0)]
        public ServiceNPS.getCredencialesRequestBody Body;
        
        public getCredencialesRequest()
        {
        }
        
        public getCredencialesRequest(ServiceNPS.getCredencialesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCredencialesRequestBody
    {
        
        public getCredencialesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCredencialesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCredencialesResponse", Namespace="http://soap.netvox.com/", Order=0)]
        public ServiceNPS.getCredencialesResponseBody Body;
        
        public getCredencialesResponse()
        {
        }
        
        public getCredencialesResponse(ServiceNPS.getCredencialesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCredencialesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCredencialesResponseBody()
        {
        }
        
        public getCredencialesResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CallChannel : ServiceNPS.Call, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CallClient : System.ServiceModel.ClientBase<ServiceNPS.Call>, ServiceNPS.Call
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CallClient() : 
                base(CallClient.GetDefaultBinding(), CallClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CallPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallClient(EndpointConfiguration endpointConfiguration) : 
                base(CallClient.GetBindingForEndpoint(endpointConfiguration), CallClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CallClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CallClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceNPS.registrarResponse> ServiceNPS.Call.registrarAsync(ServiceNPS.registrarRequest request)
        {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceNPS.registrarResponse> registrarAsync(
                    string ges_id, 
                    string ges_campana, 
                    string ges_tipo_documento, 
                    string ges_numero_documento, 
                    string ges_fec_hor, 
                    string pr_nombres_cliente, 
                    string pr_apellidos_cliente, 
                    string desc_operador, 
                    string attributeconnid, 
                    string mensaje, 
                    string base_pto_contacto, 
                    string ges_tipo_llamada, 
                    string ges_tipo_llamada_desc, 
                    string id_res_cod, 
                    string res_desc, 
                    string codigo_del_servicio, 
                    string descripcion_corta_servicio, 
                    string cod_detalle_servicio, 
                    string descripcion_corta_detalle_serv, 
                    string telefono, 
                    string campana_ivrvox, 
                    string identificador_empresa, 
                    string identificador_agente, 
                    string nombre_coordinador, 
                    string cod_personal)
        {
            ServiceNPS.registrarRequest inValue = new ServiceNPS.registrarRequest();
            inValue.Body = new ServiceNPS.registrarRequestBody();
            inValue.Body.ges_id = ges_id;
            inValue.Body.ges_campana = ges_campana;
            inValue.Body.ges_tipo_documento = ges_tipo_documento;
            inValue.Body.ges_numero_documento = ges_numero_documento;
            inValue.Body.ges_fec_hor = ges_fec_hor;
            inValue.Body.pr_nombres_cliente = pr_nombres_cliente;
            inValue.Body.pr_apellidos_cliente = pr_apellidos_cliente;
            inValue.Body.desc_operador = desc_operador;
            inValue.Body.attributeconnid = attributeconnid;
            inValue.Body.mensaje = mensaje;
            inValue.Body.base_pto_contacto = base_pto_contacto;
            inValue.Body.ges_tipo_llamada = ges_tipo_llamada;
            inValue.Body.ges_tipo_llamada_desc = ges_tipo_llamada_desc;
            inValue.Body.id_res_cod = id_res_cod;
            inValue.Body.res_desc = res_desc;
            inValue.Body.codigo_del_servicio = codigo_del_servicio;
            inValue.Body.descripcion_corta_servicio = descripcion_corta_servicio;
            inValue.Body.cod_detalle_servicio = cod_detalle_servicio;
            inValue.Body.descripcion_corta_detalle_serv = descripcion_corta_detalle_serv;
            inValue.Body.telefono = telefono;
            inValue.Body.campana_ivrvox = campana_ivrvox;
            inValue.Body.identificador_empresa = identificador_empresa;
            inValue.Body.identificador_agente = identificador_agente;
            inValue.Body.nombre_coordinador = nombre_coordinador;
            inValue.Body.cod_personal = cod_personal;
            return ((ServiceNPS.Call)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceNPS.getCredencialesResponse> ServiceNPS.Call.getCredencialesAsync(ServiceNPS.getCredencialesRequest request)
        {
            return base.Channel.getCredencialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceNPS.getCredencialesResponse> getCredencialesAsync()
        {
            ServiceNPS.getCredencialesRequest inValue = new ServiceNPS.getCredencialesRequest();
            inValue.Body = new ServiceNPS.getCredencialesRequestBody();
            return ((ServiceNPS.Call)(this)).getCredencialesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CallPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CallPort))
            {
                return new System.ServiceModel.EndpointAddress("https://www.ccf.com.pe/ivrbridge/Call");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CallClient.GetBindingForEndpoint(EndpointConfiguration.CallPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CallClient.GetEndpointAddress(EndpointConfiguration.CallPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CallPort,
        }
    }
}
